import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { FarmApiService, EggLog } from '../core/farm-api.service';

type EggLogDraft = Omit<EggLog, 'id' | 'createdBy'>;
const today = new Date().toISOString().slice(0, 10);
const blank = (): EggLogDraft => ({ date: today, totalEggs: 0, crackedEggs: 0, feedConsumedKg: 0, vitaminInWater: '', vitaminInFeed: '', notes: '', typeC: 0, typeB: 0, typeA: 0, typeAa: 0, typeAaa: 0, typeJumbo: 0 });
@Component({ selector:'app-egg-logs',imports:[FormsModule],template:`<section><p class="eyebrow">OPERACIÓN DIARIA</p><h1>Recolección y clasificación</h1><div class="layout"><form (ngSubmit)="save()"><h2>Registrar el día</h2><div class="fields"><label>Fecha<input type="date" [(ngModel)]="form.date" name="date" required></label><label>Huevos recogidos<input type="number" [(ngModel)]="form.totalEggs" name="total" min="0"></label><label>Quebrados<input type="number" [(ngModel)]="form.crackedEggs" name="cracked" min="0"></label><label>Alimento (kg)<input type="number" [(ngModel)]="form.feedConsumedKg" name="feed" min="0.01" step="0.01"></label><label>Vitamina en agua<input [(ngModel)]="form.vitaminInWater" name="water"></label><label>Vitamina en alimento<input [(ngModel)]="form.vitaminInFeed" name="feedVitamin"></label></div><h3>Clasificación</h3><div class="sizes"><label>C<input type="number" [(ngModel)]="form.typeC" name="c"></label><label>B<input type="number" [(ngModel)]="form.typeB" name="b"></label><label>A<input type="number" [(ngModel)]="form.typeA" name="a"></label><label>AA<input type="number" [(ngModel)]="form.typeAa" name="aa"></label><label>AAA<input type="number" [(ngModel)]="form.typeAaa" name="aaa"></label><label>Jumbo<input type="number" [(ngModel)]="form.typeJumbo" name="jumbo"></label></div><label>Notas<textarea [(ngModel)]="form.notes" name="notes"></textarea></label>@if(message()){<p class="message">{{message()}}</p>}<button>Guardar recolección</button></form><article><h2>Registros recientes</h2>@for(log of logs();track log.id){<div class="log"><strong>{{log.date}}</strong><span>{{log.totalEggs}} recogidos · {{log.crackedEggs}} quebrados · {{log.feedConsumedKg}} kg</span><small>C {{log.typeC}} · B {{log.typeB}} · A {{log.typeA}} · AA {{log.typeAa}} · AAA {{log.typeAaa}} · Jumbo {{log.typeJumbo}}</small></div>}@empty{<p>No hay recolecciones.</p>}</article></div></section>`,styles:`.eyebrow{color:#6f845f;font-weight:800;letter-spacing:.1em}h1{font-size:2rem}.layout{display:grid;gap:1rem;grid-template-columns:minmax(0,1.1fr) minmax(300px,.9fr)}form,article{background:#fff;border:1px solid #e2dfd2;border-radius:1.25rem;padding:1.25rem}.fields,.sizes{display:grid;gap:.75rem;grid-template-columns:repeat(2,minmax(0,1fr))}.sizes{grid-template-columns:repeat(3,minmax(0,1fr))}label{display:grid;gap:.35rem;font-weight:700}input,textarea{border:1px solid #ccd4c5;border-radius:.6rem;font:inherit;padding:.65rem}textarea{min-height:70px}button{background:#496547;border:0;border-radius:999px;color:#fff;font-weight:800;margin-top:1rem;padding:.85rem 1.25rem}.log{border-top:1px solid #eee8dc;display:grid;gap:.3rem;padding:1rem 0}.log small{color:#637266}.message{color:#a63232}@media(max-width:800px){.layout{grid-template-columns:1fr}.fields{grid-template-columns:1fr}.sizes{grid-template-columns:repeat(2,1fr)}}`})
export class EggLogsPage implements OnInit { form=blank();readonly logs=signal<EggLog[]>([]);readonly message=signal('');constructor(private readonly api:FarmApiService){}ngOnInit(){this.load();}load(){this.api.eggLogs().subscribe(logs=>this.logs.set(logs));}save(){this.message.set('');this.api.createEggLog(this.form).subscribe({next:()=>{this.form=blank();this.message.set('Recolección guardada.');this.load();},error:response=>this.message.set(response.error?.error ?? 'No se pudo guardar el registro.')});}}
